"""
VEDA — Autonomous Data Science System
agents/mlops/model_serving.py — Model Serving Agent

Wraps trained model in a FastAPI endpoint:
- /predict — single prediction
- /predict/batch — batch predictions
- /health — health check
- /metrics — model metrics
"""

import os
import json
import joblib
import pandas as pd
import numpy as np
from datetime import datetime
from dotenv import load_dotenv

from veda.core.base_agent import BaseAgent

load_dotenv()


class ModelServingAgent(BaseAgent):

    def __init__(self):
        super().__init__(
            name="ModelServingAgent",
            domain="mlops",
            version="1.0.0"
        )

    def _load_model(self, state: dict):
        """Load trained model from outputs."""
        model_info = state.get("model_info", {})
        model_path = model_info.get("model_path")
        if model_path and os.path.exists(model_path):
            return joblib.load(model_path)
        d = "outputs"
        files = [f for f in os.listdir(d) if f.endswith("_model.pkl")]
        if not files:
            return None
        return joblib.load(os.path.join(d, sorted(files)[-1]))

    def _load_feature_names(self, state: dict) -> list:
        """Load feature names."""
        feature_list = state.get("feature_list", [])
        if feature_list:
            return feature_list
        d = "outputs"
        files = [f for f in os.listdir(d) if f.endswith("_features.parquet")]
        if files:
            df = pd.read_parquet(os.path.join(d, sorted(files)[-1]))
            target = state.get("data_profile", {}).get("target_column") if state.get("data_profile") else None
            cols = [c for c in df.columns if c != target]
            return cols
        return []

    def _generate_fastapi_app(self, model_name: str, feature_names: list,
                               metrics: dict, run_id: str) -> str:
        """Generate FastAPI application code."""

        features_str = str(feature_names[:20])
        metrics_str = json.dumps(metrics, indent=4)

        app_code = '''"""
VEDA Model Serving API
Auto-generated by VEDA ModelServingAgent
Model: ''' + model_name + '''
Run ID: ''' + run_id + '''
"""

import os
import joblib
import pandas as pd
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
from datetime import datetime
import uvicorn

app = FastAPI(
    title="VEDA Model API",
    description="Auto-generated ML model serving API by VEDA",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"]
)

# ── Load model ────────────────────────────────────────────────
MODEL_PATH = "outputs/''' + run_id + '''_model.pkl"
model = None
load_time = None

def load_model():
    global model, load_time
    try:
        model = joblib.load(MODEL_PATH)
        load_time = datetime.now().isoformat()
        print("Model loaded: " + MODEL_PATH)
    except Exception as e:
        print("Failed to load model: " + str(e))

load_model()

# ── Request/Response schemas ──────────────────────────────────
class PredictRequest(BaseModel):
    features: Dict[str, Any]

class PredictBatchRequest(BaseModel):
    records: List[Dict[str, Any]]

class PredictResponse(BaseModel):
    prediction: int
    probability: float
    model: str
    timestamp: str

# ── Endpoints ─────────────────────────────────────────────────
@app.get("/health")
def health_check():
    return {
        "status": "healthy" if model else "model not loaded",
        "model": "''' + model_name + '''",
        "load_time": load_time,
        "timestamp": datetime.now().isoformat()
    }

@app.get("/metrics")
def get_metrics():
    return {
        "model_name": "''' + model_name + '''",
        "metrics": ''' + metrics_str + ''',
        "feature_count": ''' + str(len(feature_names)) + ''',
        "run_id": "''' + run_id + '''"
    }

@app.get("/features")
def get_features():
    return {
        "features": ''' + features_str + ''',
        "count": ''' + str(len(feature_names)) + '''
    }

@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest):
    if not model:
        raise HTTPException(status_code=503, detail="Model not loaded")
    try:
        df = pd.DataFrame([request.features])
        prediction = int(model.predict(df)[0])
        probability = float(model.predict_proba(df)[0][1])
        return PredictResponse(
            prediction=prediction,
            probability=round(probability, 4),
            model="''' + model_name + '''",
            timestamp=datetime.now().isoformat()
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/predict/batch")
def predict_batch(request: PredictBatchRequest):
    if not model:
        raise HTTPException(status_code=503, detail="Model not loaded")
    try:
        df = pd.DataFrame(request.records)
        predictions = model.predict(df).tolist()
        probabilities = model.predict_proba(df)[:, 1].tolist()
        return {
            "predictions": predictions,
            "probabilities": [round(p, 4) for p in probabilities],
            "count": len(predictions),
            "timestamp": datetime.now().isoformat()
        }
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
        return app_code

    def _generate_dockerfile(self, run_id: str) -> str:
        """Generate Dockerfile for the serving API."""
        return '''FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install fastapi uvicorn joblib pandas numpy scikit-learn lightgbm xgboost --no-cache-dir

COPY outputs/''' + run_id + '''_model.pkl outputs/
COPY veda_api.py .

EXPOSE 8000

CMD ["python", "veda_api.py"]
'''

    def run(self, state: dict) -> dict:
        """
        Model Serving:
        1. Load trained model
        2. Generate FastAPI app
        3. Generate Dockerfile
        4. Save deployment artifacts
        """

        self.log("Loading model for serving...")
        model = self._load_model(state)

        if model is None:
            self.log("No model found to serve", level="WARN")
            return state

        model_info = state.get("model_info", {})
        model_name = model_info.get("model_name", "MLModel")
        metrics = model_info.get("test_metrics", {})
        feature_names = self._load_feature_names(state)
        run_id = state.get("run_id", datetime.now().strftime("%Y%m%d_%H%M%S"))

        self.log("Model: " + model_name)
        self.log("Features: " + str(len(feature_names)))

        # Generate FastAPI app
        self.log("Generating FastAPI serving app...")
        app_code = self._generate_fastapi_app(
            model_name, feature_names, metrics, run_id
        )

        os.makedirs("outputs", exist_ok=True)
        api_path = "outputs/veda_api.py"
        with open(api_path, "w", encoding="utf-8") as f:
            f.write(app_code)
        self.log("FastAPI app saved to: " + api_path)

        # Generate Dockerfile
        dockerfile = self._generate_dockerfile(run_id)
        dockerfile_path = "outputs/Dockerfile"
        with open(dockerfile_path, "w") as f:
            f.write(dockerfile)
        self.log("Dockerfile saved to: " + dockerfile_path)

        # Generate curl examples
        curl_examples = {
            "health_check": "curl http://localhost:8000/health",
            "get_metrics": "curl http://localhost:8000/metrics",
            "single_predict": 'curl -X POST http://localhost:8000/predict -H "Content-Type: application/json" -d \'{"features": ' + str({f: 0 for f in feature_names[:3]}) + "}\'",
            "run_api": "python outputs/veda_api.py"
        }

        serving_info = {
            "model_name": model_name,
            "api_path": api_path,
            "dockerfile_path": dockerfile_path,
            "endpoints": ["/health", "/metrics", "/features", "/predict", "/predict/batch"],
            "feature_count": len(feature_names),
            "curl_examples": curl_examples,
            "run_command": "python outputs/veda_api.py"
        }

        info_path = "outputs/" + run_id + "_serving_info.json"
        with open(info_path, "w") as f:
            json.dump(serving_info, f, indent=2)

        state["serving_info"] = serving_info
        state.setdefault("planner_decision_log", []).append(
            "[" + datetime.now().isoformat() + "] ModelServingAgent: FastAPI app generated for " + model_name
        )

        self.log("=" * 50)
        self.log("MODEL SERVING COMPLETE")
        self.log("API file    : " + api_path)
        self.log("Dockerfile  : " + dockerfile_path)
        self.log("Endpoints   : " + str(serving_info["endpoints"]))
        self.log("Run with    : python outputs/veda_api.py")
        self.log("=" * 50)

        return state